Update pairSum.cpp
Kavya-24/Snippets pull request #383
Opened 2024-10-04 13:40 UTC by devank21

#hacktoberfest2024

# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #issue_number_here 

# Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Change in documentation

 
# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] Necessary documentation changes done
- [ ] I have added the file in the correct directory

# Screenshots / Video:

2024-10-05 10:31 UTC, Kavya-24 requested changes

2024-10-05 10:31 UTC, Kavya-24 commented on Algorithms/2Pointer Algorithm/pairSum.cpp
> +        int target=arr[target]+arr[end];
```suggestion
        int target=arr[start]+arr[end];
```

2024-10-05 10:37 UTC, devank21 commented
done

2024-10-06 18:49 UTC, Kavya-24 approved these changes

2024-10-06 18:49 UTC, merged